[gravity]
domain = "gravity"
host = "0.0.0.0"
port = 32803
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1

[adapter]
adapterID = "debezium_adapter"
adapterName = "Debezium Adapter"

# Authentication
appID = "anonymous"
accessKey = ""

[source]
config = "./settings/sources.json"
